name: Maketest

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    container: smauzerrichard/mosze:2.0
    steps:
      - uses: actions/checkout@v2
      - name: Creating cppcheck artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_report
          path: cppcheck_report.txt
      - name: Build 
        run: make test

