name: Rpg workflow

on:
  push:
    branch: [init]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp -o fig
      - run: ./run_fight.sh fig
      