name: Rpg workflow

on:
  push:
    branch: [levelup]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the application
        run: g++ -std=c++17 *.cpp -o rpg
      - name: Make ./run_fight.sh executable
        run: chmod +x ./run_fight.sh
      - name: Run input-output tests
        run: ./run_fight.sh rpg generated_output.txt
      - name: Check resoult of input output tets
        run: diff -w -B generated_output.txt good_output.txt 